<?xml version="1.0" encoding="utf-8"?><Database Name="EXIMAGEN_NUEVAB" Class="EXIMSAPDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.130.37.40;Initial Catalog=EXIMAGEN_NUEVAB;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EXIMAGEN_NUEVABConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.OCRD" Member="OCRD">
    <Type Name="OCRD">
      <Column Name="CardCode" Type="System.String" DbType="NVarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CardName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CardType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="GroupCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CmpPrivate" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MailAddres" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MailZipCod" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Phone1" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Phone2" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CntctPrsn" Type="System.String" DbType="NVarChar(90)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ChecksBal" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DNotesBal" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="OrdersBal" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="GroupNum" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CreditLine" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DebtLine" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="LicTradNum" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="DdctStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DdctPrcnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ValidUntil" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Chrctrstcs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExMatchNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InMatchNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ListNum" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DNoteBalFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="OrderBalFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DNoteBalSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="OrderBalSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Transfered" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BalTrnsfrd" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="IntrstRate" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Commission" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CommGrCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Free_Text" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SlpCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrevYearAc" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="RateDifAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BalanceSys" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BalanceFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Protected" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Cellular" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AvrageLate" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="County" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="MailCity" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MailCounty" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MailCountr" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="E_Mail" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Picture" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DflAccount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DflBranch" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BankCode" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="AddID" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Pager" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="FatherCard" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="CardFName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FatherType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup1" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup2" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup3" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup4" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup5" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup6" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup7" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup8" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup9" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup10" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup11" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup12" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup13" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup14" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup15" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup16" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup17" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup18" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup19" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup20" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup21" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup22" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup23" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup24" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup25" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup26" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup27" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup28" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup29" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup30" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup31" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup32" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup33" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup34" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup35" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup36" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup37" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup38" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup39" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup40" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup41" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup42" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup43" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup44" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup45" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup46" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup47" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup48" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup49" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup50" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup51" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup52" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup53" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup54" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup55" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup56" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup57" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup58" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup59" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup60" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup61" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup62" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup63" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QryGroup64" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DdctOffice" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExportCode" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="DscntObjct" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DscntRel" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="SPGCounter" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SPPCounter" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DdctFileNo" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="SCNCounter" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MinIntrst" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DataSource" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="OprCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExemptNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreditCard" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CrCardNum" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="CardValid" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserSign" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="LocMth" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="validFor" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="validFrom" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="validTo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="frozenFor" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="frozenFrom" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="frozenTo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sEmployed" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="MTHCounter" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BNKCounter" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DdgKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DdtKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValidComm" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="FrozenComm" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="chainStore" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DiscInRet" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="State1" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="State2" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="VatGroup" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="LogInstanc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ObjType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Indicator" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ShipType" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DebPayAcct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ShipToDef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Block" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MailBlock" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="ECVatGroup" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="IBAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DocEntry" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FormCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Box1099" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PymCode" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BackOrder" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PartDelivr" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DunnLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DunnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BlockDunn" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BankCountr" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="CollecAuth" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DME" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="InstrucKey" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SinglePaym" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ISRBillId" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="PaymBlock" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RefDetails" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HouseBank" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="OwnerIdNum" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PyBlckDesc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HousBnkCry" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="HousBnkAct" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HousBnkBrn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProjectCod" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SysMatchNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VatIdUnCmp" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="TolrncDays" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SelfInvoic" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DeferrTax" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="LetterNum" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MaxAmount" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WTLiable" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CrtfcateNO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ExpireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NINum" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="AccCritria" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="WTCode" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Equ" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="HldCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ConnBP" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="MltMthNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypWTReprt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VATRegNum" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="RepName" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Industry" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Business" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="WTTaxCat" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsDomestic" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="IsResident" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AutoCalBCG" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="OtrCtlAcct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="AliasName" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Building" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MailBuildi" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BoEPrsnt" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BoEDiscnt" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BoEOnClct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="UnpaidBoE" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ITWTCode" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="DunTerm" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="ChannlBP" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="DfTcnician" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Territory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BillToDef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DpmClear" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="IntrntSite" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LangCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HousActKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Profession" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CDPNum" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DflBankKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BCACode" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="UseShpdGd" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RegNum" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="VerifNum" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="BankCtlKey" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="HousCtlKey" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="AddrType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="InsurOp347" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="MailAddrTy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StreetNo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MailStrNo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TaxRndRule" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VendTID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThreshOver" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="SurOver" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VendorOcup" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="OpCode347" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DpmIntAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ResidenNum" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="UserSign2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PlngGroup" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="VatIDNum" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Affiliate" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="MivzExpSts" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="HierchDdct" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CertWHT" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CertBKeep" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="WHShaamGrp" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="IndustryC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DatevAcct" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="DatevFirst" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="GTSRegNum" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GTSBankAct" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="GTSBilAddr" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="HsBnkSwift" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HsBnkIBAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DflSwift" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AutoPost" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="IntrAcc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="FeeAcc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="CpnNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NTSWebSite" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DflIBAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Series" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDocExpFrm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TaxIdIdent" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Attachment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AtcEntry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiscRel" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NoDiscount" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="SCAdjust" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DflAgrmnt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GlblLocNum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SenderID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RcpntID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MainUsage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SefazCheck" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="free312" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="free313" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DateFrom" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateTill" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RelCode" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="OKATO" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="OKTMO" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="KBKCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TypeOfOp" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="OwnerCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MandateID" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
      <Column Name="SignDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remark1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConCerti" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TpCusPres" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleTypCod" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="BlockComm" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EmplymntCt" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ExcptnlEvt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ExpnPrfFnd" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EdrsFromBP" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EdrsToBP" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CreateTS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateTS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDocGenTyp" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="eStreet" Type="System.String" DbType="NVarChar(38)" CanBeNull="true" />
      <Column Name="eStreetNum" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="eBuildnNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="eZipCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="eCityTown" Type="System.String" DbType="NVarChar(48)" CanBeNull="true" />
      <Column Name="eCountry" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="eDistrict" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="RepFName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="RepSName" Type="System.String" DbType="NVarChar(36)" CanBeNull="true" />
      <Column Name="RepCmpName" Type="System.String" DbType="NVarChar(36)" CanBeNull="true" />
      <Column Name="RepFisCode" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="RepAddID" Type="System.String" DbType="NVarChar(28)" CanBeNull="true" />
      <Column Name="PECAddr" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="IPACodePA" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="PriceMode" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EffecPrice" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="TxExMxVdTp" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="MerchantID" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="UseBilAddr" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NaturalPer" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DPPStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EnAddID" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EncryptIV" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EnDflAccnt" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EnDflIBAN" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EnERD4In" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EnERD4Out" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DflCustomr" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="TspEntry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TspLine" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FCERelevnt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_Tipo" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="U_NClave" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="U_Email" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="U_DocEnviar" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="U_Plus" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="U_Fechap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="U_COFACE" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="U_FechaC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="U_eximagen" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="U_FechaE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="U_Suma" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="U_SoObs" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="U_CuotaAn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_CuotaAj" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PreSup_Ene" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PreSup_Feb" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PreSup_Mar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_Presup_Q1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PreSup_Abr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PreSup_May" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PreSup_Jun" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_Presup_Q2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PreSup_Jul" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PreSup_Ago" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PreSup_Sep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_Presup_Q3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PreSup_Oct" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PreSup_Nov" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PreSup_Dic" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_Presup_Q4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_idasesor" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="U_Perfil" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="U_ClienteMostrador" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_Correos" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="U_EmailP" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="U_DocEnviarP" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="U_ClienteExtranjero" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_MetodoPago" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="U_Cuenta" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="U_2013" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="U_PCS_ID_PAY_TERM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PCS_ID_def_Port" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PCS_ID_App_status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PCS_Quality" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PCS_Consitency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PCS_Time" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PCS_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PCS_ID_FINAL_RISK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_B1SYS_MainUsage" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="U_TipoPago" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="U_Origen" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Traslados_pruebas" Method="Traslados_pruebas">
    <Parameter Name="DocDate" Parameter="docDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DocDueDate" Parameter="docDueDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ITEM" Parameter="iTEM" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="AlmacenO" Parameter="almacenO" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="AlmacenD" Parameter="almacenD" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="PARTIDA" Parameter="pARTIDA" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="Factura" Parameter="factura" Type="System.String" DbType="VarChar(12)" />
    <Return Type="System.Int32" />
  </Function>
</Database>