///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the table 'NotasCredito'
// Generated by LLBLGen v1.21.2003.712 Final on: Miércoles, 07 de Julio de 2010, 09:49:03 p.m.
// Because the Base Class already implements IDispose, this class doesn't.
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;
using Componente.Conexion;
namespace Componente.Procesos
{
	/// <summary>
	/// Purpose: Data Access class for the table 'NotasCredito'.
	/// </summary>
	public class NotasCredito : DBInteractionBase
	{
		#region Class Member Declarations
			private SqlDateTime		_notasCreditoFechaNotaCre;
            private SqlInt32 _notasCreditoNumFacOrigenSap, _notasCreditoId, _notasCreditoIdSap, _notasCreditoDocNum;
			private SqlString		_notasCreditoNombreClien, _notasCreditoNumClien;
		#endregion


		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public NotasCredito()
		{
			// Nothing for now.
		}


		/// <summary>
		/// Purpose: Insert method. This method will insert one new row into the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>NotasCreditoIdSap</LI>
		///		 <LI>NotasCreditoNumFacOrigenSap</LI>
		///		 <LI>NotasCreditoNumClien</LI>
		///		 <LI>NotasCreditoFechaNotaCre</LI>
		///		 <LI>NotasCreditoNombreClien</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>NotasCreditoId</LI>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public override bool Insert()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[sp_post_NotasCredito_Insert]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@iNotasCreditoIdSap", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, _notasCreditoIdSap));
				cmdToExecute.Parameters.Add(new SqlParameter("@iNotasCreditoNumFacOrigenSap", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, _notasCreditoNumFacOrigenSap));
				cmdToExecute.Parameters.Add(new SqlParameter("@sNotasCreditoNumClien", SqlDbType.VarChar, 30, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _notasCreditoNumClien));
				cmdToExecute.Parameters.Add(new SqlParameter("@daNotasCreditoFechaNotaCre", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _notasCreditoFechaNotaCre));
				cmdToExecute.Parameters.Add(new SqlParameter("@sNotasCreditoNombreClien", SqlDbType.VarChar, 200, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _notasCreditoNombreClien));
				cmdToExecute.Parameters.Add(new SqlParameter("@iNotasCreditoId", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _notasCreditoId));
				cmdToExecute.Parameters.Add(new SqlParameter("@iErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				_notasCreditoId = (Int32)cmdToExecute.Parameters["@iNotasCreditoId"].Value;
				_errorCode = (Int32)cmdToExecute.Parameters["@iErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'sp_post_NotasCredito_Insert' reported the ErrorCode: " + _errorCode);
				}

				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("NotasCredito::Insert::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Update method. This method will Update one existing row in the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>NotasCreditoId</LI>
		///		 <LI>NotasCreditoIdSap</LI>
		///		 <LI>NotasCreditoNumFacOrigenSap</LI>
		///		 <LI>NotasCreditoNumClien</LI>
		///		 <LI>NotasCreditoFechaNotaCre</LI>
		///		 <LI>NotasCreditoNombreClien</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public override bool Update()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[sp_post_NotasCredito_Update]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@iNotasCreditoId", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, _notasCreditoId));
				cmdToExecute.Parameters.Add(new SqlParameter("@iNotasCreditoIdSap", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, _notasCreditoIdSap));
				cmdToExecute.Parameters.Add(new SqlParameter("@iNotasCreditoNumFacOrigenSap", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, _notasCreditoNumFacOrigenSap));
				cmdToExecute.Parameters.Add(new SqlParameter("@sNotasCreditoNumClien", SqlDbType.VarChar, 30, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _notasCreditoNumClien));
				cmdToExecute.Parameters.Add(new SqlParameter("@daNotasCreditoFechaNotaCre", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _notasCreditoFechaNotaCre));
				cmdToExecute.Parameters.Add(new SqlParameter("@sNotasCreditoNombreClien", SqlDbType.VarChar, 200, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _notasCreditoNombreClien));
				cmdToExecute.Parameters.Add(new SqlParameter("@iErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				_errorCode = (Int32)cmdToExecute.Parameters["@iErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'sp_post_NotasCredito_Update' reported the ErrorCode: " + _errorCode);
				}

				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("NotasCredito::Update::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Delete method. This method will Delete one existing row in the database, based on the Primary Key.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>NotasCreditoId</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public override bool Delete()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[sp_post_NotasCredito_Delete]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@iNotasCreditoId", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, _notasCreditoId));
				cmdToExecute.Parameters.Add(new SqlParameter("@iErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				_errorCode = (Int32)cmdToExecute.Parameters["@iErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'sp_post_NotasCredito_Delete' reported the ErrorCode: " + _errorCode);
				}

				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("NotasCredito::Delete::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Select method. This method will Select one existing row from the database, based on the Primary Key.
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>NotasCreditoId</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		///		 <LI>NotasCreditoId</LI>
		///		 <LI>NotasCreditoIdSap</LI>
		///		 <LI>NotasCreditoNumFacOrigenSap</LI>
		///		 <LI>NotasCreditoNumClien</LI>
		///		 <LI>NotasCreditoFechaNotaCre</LI>
		///		 <LI>NotasCreditoNombreClien</LI>
		/// </UL>
		/// Will fill all properties corresponding with a field in the table with the value of the row selected.
		/// </remarks>
		public override DataTable SelectOne()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[sp_post_NotasCredito_SelectOne]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable toReturn = new DataTable("NotasCredito");
			SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@iNotasCreditoId", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, _notasCreditoId));
				cmdToExecute.Parameters.Add(new SqlParameter("@iErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				adapter.Fill(toReturn);
				_errorCode = (Int32)cmdToExecute.Parameters["@iErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'sp_post_NotasCredito_SelectOne' reported the ErrorCode: " + _errorCode);
				}

				if(toReturn.Rows.Count > 0)
				{
					_notasCreditoId = (Int32)toReturn.Rows[0]["NotasCreditoId"];
					_notasCreditoIdSap = (Int32)toReturn.Rows[0]["NotasCreditoIdSap"];
					_notasCreditoNumFacOrigenSap = (Int32)toReturn.Rows[0]["NotasCreditoNumFacOrigenSap"];
					_notasCreditoNumClien = (string)toReturn.Rows[0]["NotasCreditoNumClien"];
					_notasCreditoFechaNotaCre = (DateTime)toReturn.Rows[0]["NotasCreditoFechaNotaCre"];
					_notasCreditoNombreClien = (string)toReturn.Rows[0]["NotasCreditoNombreClien"];
				}
				return toReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("NotasCredito::SelectOne::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
				adapter.Dispose();
			}
		}
        public  DataTable SelectOne_NC()
        {
            SqlCommand cmdToExecute = new SqlCommand();
            cmdToExecute.CommandText = "dbo.[sp_post_NotasCredito_SelectOneNT]";
            cmdToExecute.CommandType = CommandType.StoredProcedure;
            DataTable toReturn = new DataTable("NotasCredito");
            SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

            // Use base class' connection object
            cmdToExecute.Connection = _mainConnection;

            try
            {
                cmdToExecute.Parameters.Add(new SqlParameter("@iNotasCreditoNumFacOrigenSap", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, _notasCreditoNumFacOrigenSap));
                cmdToExecute.Parameters.Add(new SqlParameter("@iErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

                if (_mainConnectionIsCreatedLocal)
                {
                    // Open connection.
                    _mainConnection.Open();
                }
                else
                {
                    if (_mainConnectionProvider.IsTransactionPending)
                    {
                        cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
                    }
                }

                // Execute query.
                adapter.Fill(toReturn);
                _errorCode = (SqlInt32)cmdToExecute.Parameters["@iErrorCode"].Value;

                if (_errorCode != (int)LLBLError.AllOk)
                {
                    // Throw error.
                    throw new Exception("Stored Procedure 'sp_post_NotasCredito_SelectOne' reported the ErrorCode: " + _errorCode);
                }

                if (toReturn.Rows.Count > 0)
                {
                    _notasCreditoDocNum = (Int32)toReturn.Rows[0]["NotasCreditoDocNum"];
                 
                }
                return toReturn;
            }
            catch (Exception ex)
            {
                // some error occured. Bubble it to caller and encapsulate Exception object
                throw new Exception("NotasCredito::SelectOne::Error occured.", ex);
            }
            finally
            {
                if (_mainConnectionIsCreatedLocal)
                {
                    // Close connection.
                    _mainConnection.Close();
                }
                cmdToExecute.Dispose();
                adapter.Dispose();
            }
        }


		/// <summary>
		/// Purpose: SelectAll method. This method will Select all rows from the table.
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public override DataTable SelectAll()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[sp_post_NotasCredito_SelectAll]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable toReturn = new DataTable("NotasCredito");
			SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@iErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				adapter.Fill(toReturn);
				_errorCode = (Int32)cmdToExecute.Parameters["@iErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'sp_post_NotasCredito_SelectAll' reported the ErrorCode: " + _errorCode);
				}

				return toReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("NotasCredito::SelectAll::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
				adapter.Dispose();
			}
		}


		#region Class Property Declarations
		public SqlInt32 NotasCreditoId
		{
			get
			{
				return _notasCreditoId;
			}
			set
			{
				SqlInt32 notasCreditoIdTmp = (SqlInt32)value;
				if(notasCreditoIdTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("NotasCreditoId", "NotasCreditoId can't be NULL");
				}
				_notasCreditoId = value;
			}
		}


		public SqlInt32 NotasCreditoIdSap
		{
			get
			{
				return _notasCreditoIdSap;
			}
			set
			{
				SqlInt32 notasCreditoIdSapTmp = (SqlInt32)value;
				if(notasCreditoIdSapTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("NotasCreditoIdSap", "NotasCreditoIdSap can't be NULL");
				}
				_notasCreditoIdSap = value;
			}
		}


		public SqlInt32 NotasCreditoNumFacOrigenSap
		{
			get
			{
				return _notasCreditoNumFacOrigenSap;
			}
			set
			{
				SqlInt32 notasCreditoNumFacOrigenSapTmp = (SqlInt32)value;
				if(notasCreditoNumFacOrigenSapTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("NotasCreditoNumFacOrigenSap", "NotasCreditoNumFacOrigenSap can't be NULL");
				}
				_notasCreditoNumFacOrigenSap = value;
			}
		}


		public SqlString NotasCreditoNumClien
		{
			get
			{
				return _notasCreditoNumClien;
			}
			set
			{
				SqlString notasCreditoNumClienTmp = (SqlString)value;
				if(notasCreditoNumClienTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("NotasCreditoNumClien", "NotasCreditoNumClien can't be NULL");
				}
				_notasCreditoNumClien = value;
			}
		}


		public SqlDateTime NotasCreditoFechaNotaCre
		{
			get
			{
				return _notasCreditoFechaNotaCre;
			}
			set
			{
				SqlDateTime notasCreditoFechaNotaCreTmp = (SqlDateTime)value;
				if(notasCreditoFechaNotaCreTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("NotasCreditoFechaNotaCre", "NotasCreditoFechaNotaCre can't be NULL");
				}
				_notasCreditoFechaNotaCre = value;
			}
		}


		public SqlString NotasCreditoNombreClien
		{
			get
			{
				return _notasCreditoNombreClien;
			}
			set
			{
				SqlString notasCreditoNombreClienTmp = (SqlString)value;
				if(notasCreditoNombreClienTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("NotasCreditoNombreClien", "NotasCreditoNombreClien can't be NULL");
				}
				_notasCreditoNombreClien = value;
			}
		}

        public SqlInt32 NotasCreditoDocNum
        {
            get { return _notasCreditoDocNum; }
            set { _notasCreditoDocNum = value; }
        }
		#endregion
	}
}
